version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "mateuszkwiecinski"
  - package-ecosystem: "gradle"
    directory: "buildSrc"
    schedule:
      interval: "daily"
    assignees:
      - "mateuszkwiecinski"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "mateuszkwiecinski"
