name: Generate dependency diff

permissions:
  pull-requests: write
  issues: write
on:
  pull_request:

jobs:
  generate-diff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - uses: gradle/gradle-build-action@v2

      - run: ./gradlew assemble -m

      - id: dependency-diff
        name: Generate dependency diff
        uses: usefulness/dependency-tree-diff-action@v1
        with:
          configuration: 'runtimeClasspath'
          project: 'issuechecker'

      - uses: peter-evans/find-comment@v3
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Dependency diff

      - uses: peter-evans/create-or-update-comment@v4
        if: ${{ steps.dependency-diff.outputs.text-diff != null || steps.find_comment.outputs.comment-id != null }}
        with:
          body: |
            Dependency diff:
              ```diff
              ${{ steps.dependency-diff.outputs.text-diff }}
              ```
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
