name: Build Pull Request

on:
  pull_request:

jobs:
  cancel-previous-workflows:
    name: Cancel previous workflow runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: gradle/wrapper-validation-action@v1

      - uses: gradle/gradle-build-action@v2

      - run: ./gradlew projectCodestyle

      - run: ./gradlew assemble

      - run: ./gradlew projectCoverage

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-results
          path: "${{ github.workspace }}/**/build/reports/tests"

      - uses: actions/cache@v3
        name: Download base
        with:
          path: diffuse-source-file
          key: diffuse-${{ github.event.pull_request.base.sha }}

      - run: find . -regex ".*issuechecker/build/libs/issuechecker-[0-9SNAPSHOT\.-]*\.jar" -print | xargs -n 1 -I % cp % pull-request-artifact.jar
        shell: bash

      - id: diffuse
        uses: usefulness/diffuse-action@v0.8.0
        with:
          old-file-path: diffuse-source-file
          new-file-path: pull-request-artifact.jar

      - uses: peter-evans/find-comment@v2
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Diffuse output

      - uses: peter-evans/create-or-update-comment@v2
        if: ${{ steps.diffuse.outputs.diff-raw != null || steps.find_comment.outputs.comment-id != null }}
        with:
          body: |
            ### Jar size:
            Jar size change: ${{ steps.diffuse.outputs.size-diff-comment_style_1 }}
            ### Diffuse output:
            ${{ steps.diffuse.outputs.diff-gh-comment }}
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: diffuse-output
          path: ${{ steps.diffuse.outputs.diff-file }}