name: Publish Project to all Maven repositories

on:
  push:
    tags:
      - 'release-*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
  SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
  SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Unwrap GPG key
      env:
        GPG_KEY_CONTENTS: ${{ secrets.GPG_KEY_CONTENTS }}
        SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
      run: sudo bash -c "echo '$GPG_KEY_CONTENTS' | base64 -d > '$SIGNING_SECRET_KEY_RING_FILE'"
    - name: Build app with Gradle
      run: ./gradlew build
    - name: Publish to Github Package Registry
      run: ./gradlew publishMavenJavaPublicationToGithubRepository
    - name: Publish CLI to Github Package Registry
      run: ./gradlew publishShadowPublicationToGithubRepository
    - name: Publish to Maven Central
      run: ./gradlew publishMavenJavaPublicationToMavenCentralRepository
