name: Publish Project to all Maven repositories

on:
  push:
    tags:
      - 'v*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME_FOR_COM_GITHUB }}
  OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD_FOR_COM_GITHUB }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 24

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew assemble

      - run: ./gradlew publishAllPublicationsToMavenCentralRepository --no-configuration-cache

      - run: ./gradlew publishAllPublicationsToGithubRepository --no-configuration-cache

